# Generated by Django 3.2.3 on 2021-05-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Writers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=350)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
