# Generated by Django 3.2.3 on 2021-05-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_comment_writers'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
