# Generated by Django 3.2.3 on 2021-05-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_trainer_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_writers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
