# Generated by Django 3.2.3 on 2021-05-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_comment_writers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
